# Schema for the configuration files of the Loyalist module.

loyalist.settings:
  type: config_object
  label: Loyalist Settings
  mapping:
    interval:
      type: integer
      label: The amount of time to look at when evaluating visits.
    visits:
      type: integer
      label: The number of visits that qualify a visitor as a "loyalist".
    cooldown:
      type: integer
      label: Cooldown time after a visit before starting counting as a new visit.
